version: '3'

services: 
  server:
    build: ./server
    environment: 
      - PORT=3000
    ports:
      - 3000:3000
    depends_on: 
      - postgres

  postgres:
    container_name: postgres_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=postgresdb
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - psql-data:/var/lib/postgresql/data

volumes:
  psql-data:
    external: true